import type { Destination } from "./types";

// Prix indicatifs basse saison / résa anticipée, tarifs jeunes quand ils
// existent (Nomad -26 ans = -50%, Ouigo dès 19€, TER Zou/Occitanie réduits).
// Les liaisons longues passent souvent par Paris : durée et prix en tiennent
// compte. À vérifier avant résa.
export const destinations: Destination[] = [
  {
    slug: "dieppe",
    name: "Dieppe",
    code: "DPE",
    region: "Normandie, côte d'Albâtre",
    coords: { lat: 49.9229, lng: 1.0777 },
    vibes: ["mer"],
    tagline: "La mer la moins chère de France depuis Paris.",
    transports: {
      paris: { label: "Train Nomad (Saint-Lazare)", duration: "2h15", priceAR: 20, note: "-50% pour les -26 ans, plein tarif 20,10€ le trajet" },
      lyon: { label: "TGV + Nomad via Paris", duration: "5h", priceAR: 70 },
      lille: { label: "TER via Rouen", duration: "4h", priceAR: 48 },
      marseille: { label: "TGV + Nomad via Paris", duration: "6h30", priceAR: 92 },
      bordeaux: { label: "TGV + Nomad via Paris", duration: "6h", priceAR: 88 },
    },
    lodging: { dorm: 15, duo: 52 },
    foodPerDay: 15,
    highlights: ["Falaises de craie de Pourville", "Plage et front de mer", "Marché du samedi, port de pêche"],
    duoTip: "Camping en tente partagée : la nuit tombe sous 8€ par personne.",
    bestMonths: [5, 6, 7, 8, 9],
  },
  {
    slug: "le-treport",
    name: "Le Tréport",
    code: "LTR",
    region: "Normandie / Picardie",
    coords: { lat: 50.0594, lng: 1.3774 },
    vibes: ["mer"],
    tagline: "Falaises les plus hautes d'Europe, ambiance carte postale.",
    transports: {
      paris: { label: "Train + car Nomad", duration: "3h", priceAR: 24, note: "via Abancourt ou Dieppe" },
      lyon: { label: "TGV + car via Paris", duration: "6h", priceAR: 76 },
      lille: { label: "TER via Abbeville", duration: "3h", priceAR: 34 },
      marseille: { label: "TGV + car via Paris", duration: "7h", priceAR: 98 },
      bordeaux: { label: "TGV + car via Paris", duration: "6h30", priceAR: 94 },
    },
    lodging: { dorm: 16, duo: 55 },
    foodPerDay: 15,
    highlights: ["Funiculaire gratuit vers la falaise", "Plage de galets et casino", "Mers-les-Bains et ses villas 1900"],
    duoTip: "Combinez avec Dieppe : les deux se font en car côtier.",
    bestMonths: [5, 6, 7, 8, 9],
  },
  {
    slug: "etretat",
    name: "Étretat",
    code: "ETR",
    region: "Normandie",
    coords: { lat: 49.7069, lng: 0.2027 },
    vibes: ["mer"],
    tagline: "Les falaises que le monde entier vient voir.",
    transports: {
      paris: { label: "Train Bréauté + bus", duration: "2h45", priceAR: 32 },
      lyon: { label: "TGV + train via Paris", duration: "5h30", priceAR: 80 },
      lille: { label: "TER via Rouen + bus", duration: "4h30", priceAR: 54 },
      marseille: { label: "TGV + train via Paris", duration: "7h", priceAR: 100 },
      bordeaux: { label: "TGV + train via Paris", duration: "6h30", priceAR: 95 },
    },
    lodging: { dorm: 24, duo: 78 },
    foodPerDay: 17,
    highlights: ["Arche et Aiguille creuse", "Jardins d'Étretat", "Sentier des douaniers GR21"],
    duoTip: "Dormez au Havre (auberge HI) et venez en bus : deux fois moins cher.",
    bestMonths: [4, 5, 6, 9],
  },
  {
    slug: "deauville",
    name: "Deauville-Trouville",
    code: "DVL",
    region: "Normandie, Côte Fleurie",
    coords: { lat: 49.36, lng: 0.075 },
    vibes: ["mer"],
    tagline: "Les Planches à 2h de Paris, version étudiante possible.",
    transports: {
      paris: { label: "Train Nomad (Saint-Lazare)", duration: "2h05", priceAR: 30, note: "-50% pour les -26 ans" },
      lyon: { label: "TGV + Nomad via Paris", duration: "5h", priceAR: 76 },
      lille: { label: "TGV + Nomad via Paris", duration: "4h", priceAR: 56 },
      marseille: { label: "TGV + Nomad via Paris", duration: "6h30", priceAR: 96 },
      bordeaux: { label: "TGV + Nomad via Paris", duration: "6h", priceAR: 90 },
    },
    lodging: { dorm: 28, duo: 95 },
    foodPerDay: 19,
    highlights: ["Plage et parasols mythiques", "Trouville, le port et la criée", "Villas Belle Époque"],
    duoTip: "Trouville est moins chère que Deauville pour dormir et manger.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "saint-malo",
    name: "Saint-Malo",
    code: "SML",
    region: "Bretagne, Côte d'Émeraude",
    coords: { lat: 48.6493, lng: -2.0257 },
    vibes: ["mer"],
    tagline: "Remparts, marées géantes et granit.",
    transports: {
      paris: { label: "TGV Inoui / Ouigo", duration: "2h30", priceAR: 58, note: "dès 38€ AR en résa anticipée" },
      lyon: { label: "TGV via Paris ou direct Rennes", duration: "5h", priceAR: 88 },
      lille: { label: "TGV via Paris", duration: "4h30", priceAR: 78 },
      marseille: { label: "TGV via Paris", duration: "7h", priceAR: 105 },
      bordeaux: { label: "TGV via Rennes", duration: "5h", priceAR: 75 },
    },
    lodging: { dorm: 26, duo: 80 },
    foodPerDay: 16,
    highlights: ["Tour des remparts au coucher", "Grand Bé à marée basse", "Dinard en navette maritime"],
    duoTip: "L'auberge de jeunesse HI est à 15 min à pied des remparts.",
    bestMonths: [5, 6, 7, 8, 9],
  },
  {
    slug: "la-rochelle",
    name: "La Rochelle",
    code: "LRH",
    region: "Charente-Maritime",
    coords: { lat: 46.1603, lng: -1.1511 },
    vibes: ["mer", "ville"],
    tagline: "Vieux-Port, vélo et île de Ré à portée de pédale.",
    transports: {
      paris: { label: "TGV / Ouigo", duration: "3h", priceAR: 50, note: "Ouigo dès 19€ le trajet" },
      lyon: { label: "Intercités via Massif", duration: "4h30", priceAR: 64 },
      lille: { label: "TGV via Paris", duration: "5h", priceAR: 74 },
      marseille: { label: "TGV via Paris", duration: "6h", priceAR: 85 },
      bordeaux: { label: "TER / Intercités", duration: "2h20", priceAR: 30 },
    },
    lodging: { dorm: 25, duo: 75 },
    foodPerDay: 16,
    highlights: ["Les trois tours du Vieux-Port", "Île de Ré à vélo (pont gratuit à vélo)", "Marché central et halles"],
    duoTip: "Louez deux vélos à la journée, c'est le vrai bon plan local.",
    bestMonths: [5, 6, 7, 8, 9],
  },
  {
    slug: "biarritz",
    name: "Biarritz",
    code: "BIA",
    region: "Pays basque",
    coords: { lat: 43.4832, lng: -1.5586 },
    vibes: ["mer"],
    tagline: "Océan, surf et Pays basque.",
    transports: {
      paris: { label: "TGV / Ouigo", duration: "4h10", priceAR: 70, note: "Ouigo dès 25€ le trajet" },
      lyon: { label: "TGV via Bordeaux", duration: "6h", priceAR: 90 },
      lille: { label: "TGV via Paris", duration: "6h30", priceAR: 95 },
      marseille: { label: "Intercités via Toulouse", duration: "7h", priceAR: 88 },
      bordeaux: { label: "TER / TGV", duration: "2h", priceAR: 28 },
    },
    lodging: { dorm: 30, duo: 95 },
    foodPerDay: 18,
    highlights: ["Côte des Basques au coucher", "Rocher de la Vierge", "Bayonne et Saint-Jean-de-Luz en TER"],
    duoTip: "Auberge côté Anglet : moins cher et à 10 min de plage.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "marseille",
    name: "Marseille",
    code: "MRS",
    region: "Provence, Méditerranée",
    coords: { lat: 43.2965, lng: 5.3698 },
    vibes: ["mer", "ville"],
    tagline: "Calanques, Vieux-Port et soleil quasi garanti.",
    transports: {
      paris: { label: "Ouigo", duration: "3h30", priceAR: 44, note: "dès 19€ le trajet en résa anticipée" },
      lyon: { label: "Ouigo / TGV", duration: "1h45", priceAR: 32, note: "dès 16€ le trajet" },
      lille: { label: "TGV direct", duration: "4h40", priceAR: 70 },
      bordeaux: { label: "Intercités direct", duration: "5h30", priceAR: 58 },
    },
    lodging: { dorm: 28, duo: 78 },
    foodPerDay: 16,
    highlights: ["Calanque de Sormiou en bus + marche", "Vieux-Port et le Panier", "Plages du Prado gratuites"],
    duoTip: "Le bus 21 vers Luminy : les calanques pour 1,70€.",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    slug: "cassis",
    name: "Cassis",
    code: "CSS",
    region: "Provence",
    coords: { lat: 43.214, lng: 5.5396 },
    vibes: ["mer"],
    tagline: "Le village des calanques, eau turquoise.",
    transports: {
      paris: { label: "Ouigo Marseille + TER", duration: "4h", priceAR: 52 },
      lyon: { label: "TGV Marseille + TER", duration: "2h30", priceAR: 42 },
      lille: { label: "TGV Marseille + TER", duration: "5h15", priceAR: 78 },
      marseille: { label: "TER", duration: "25 min", priceAR: 12, note: "puis bus M08 vers le port" },
      bordeaux: { label: "Intercités Marseille + TER", duration: "6h15", priceAR: 66 },
    },
    lodging: { dorm: 30, duo: 92 },
    foodPerDay: 18,
    highlights: ["Calanques d'En-Vau et Port-Pin", "Port de Cassis à l'apéro", "Cap Canaille, route des Crêtes"],
    duoTip: "Dormez à Marseille, venez en TER (25 min) : Cassis coûte cher la nuit.",
    bestMonths: [5, 6, 9],
  },
  {
    slug: "sete",
    name: "Sète",
    code: "SET",
    region: "Occitanie, Méditerranée",
    coords: { lat: 43.4075, lng: 3.6935 },
    vibes: ["mer"],
    tagline: "La Venise du Languedoc, plages de sable infinies.",
    transports: {
      paris: { label: "Ouigo direct", duration: "3h45", priceAR: 44, note: "dès 19€ le trajet en résa anticipée" },
      lyon: { label: "TER / TGV via Montpellier", duration: "2h45", priceAR: 40 },
      lille: { label: "TGV via Paris ou Lyon", duration: "5h45", priceAR: 78 },
      marseille: { label: "TER direct", duration: "2h", priceAR: 28, note: "tarif jeune Occitanie possible" },
      bordeaux: { label: "Intercités via Toulouse", duration: "4h15", priceAR: 46 },
    },
    lodging: { dorm: 27, duo: 72 },
    foodPerDay: 15,
    highlights: ["Plage de la Corniche et lido", "Mont Saint-Clair au coucher", "Canaux, halles et tielles"],
    duoTip: "Les 12 km de lido se longent à vélo, location à la journée pas chère.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "collioure",
    name: "Collioure",
    code: "COL",
    region: "Côte Vermeille, Pyrénées-Orientales",
    coords: { lat: 42.5251, lng: 3.0837 },
    vibes: ["mer"],
    tagline: "Le village des peintres, entre mer et Pyrénées.",
    transports: {
      paris: { label: "TGV Perpignan + TER", duration: "5h30", priceAR: 78 },
      lyon: { label: "TGV Perpignan + TER", duration: "4h", priceAR: 56 },
      lille: { label: "TGV via Paris + TER", duration: "7h", priceAR: 98 },
      marseille: { label: "TER via Narbonne", duration: "3h30", priceAR: 42 },
      bordeaux: { label: "Intercités via Toulouse + TER", duration: "4h45", priceAR: 52 },
    },
    lodging: { dorm: 29, duo: 88 },
    foodPerDay: 17,
    highlights: ["Château royal et clocher iconique", "Criques du sentier littoral", "Anchois et vin doux locaux"],
    duoTip: "Argelès à 10 min en TER : camping bien moins cher.",
    bestMonths: [5, 6, 9],
  },
  {
    slug: "nice",
    name: "Nice",
    code: "NCE",
    region: "Côte d'Azur",
    coords: { lat: 43.7102, lng: 7.262 },
    vibes: ["mer", "ville"],
    tagline: "La Baie des Anges au tarif Ouigo.",
    transports: {
      paris: { label: "Ouigo direct", duration: "6h", priceAR: 60, note: "dès 19€ le trajet, le plus long mais le plus dépaysant" },
      lyon: { label: "TGV direct", duration: "4h30", priceAR: 56 },
      lille: { label: "TGV via Paris ou Marseille", duration: "7h", priceAR: 88 },
      marseille: { label: "TER Zou / TGV", duration: "2h40", priceAR: 34, note: "TER Zou à 1€ certains jours d'été" },
      bordeaux: { label: "TGV via Marseille", duration: "8h", priceAR: 92 },
    },
    lodging: { dorm: 29, duo: 85 },
    foodPerDay: 17,
    highlights: ["Promenade des Anglais à l'aube", "Vieux-Nice et colline du Château", "Villefranche-sur-Mer en TER (10 min)"],
    duoTip: "TER Zou à 1€ le trajet certains jours d'été le long de la côte.",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    slug: "annecy",
    name: "Annecy",
    code: "ANN",
    region: "Haute-Savoie",
    coords: { lat: 45.8992, lng: 6.1294 },
    vibes: ["lac", "montagne"],
    tagline: "Le lac le plus photogénique de France.",
    transports: {
      paris: { label: "TGV", duration: "3h50", priceAR: 60 },
      lyon: { label: "TER direct", duration: "2h", priceAR: 26 },
      lille: { label: "TGV via Paris ou Lyon", duration: "5h30", priceAR: 82 },
      marseille: { label: "TGV Lyon + TER", duration: "4h", priceAR: 54 },
      bordeaux: { label: "TGV via Paris ou Lyon", duration: "6h30", priceAR: 92 },
    },
    lodging: { dorm: 28, duo: 85 },
    foodPerDay: 17,
    highlights: ["Baignade au Pâquier, eau à 24°C l'été", "Tour du lac à vélo (42 km)", "Vieille ville et canaux"],
    duoTip: "L'auberge HI est sur les hauteurs : vue lac au petit-déj.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "gerardmer",
    name: "Gérardmer",
    code: "GER",
    region: "Vosges",
    coords: { lat: 48.0736, lng: 6.8785 },
    vibes: ["lac", "montagne"],
    tagline: "Lac, forêts et fraîcheur vosgienne, budget mini.",
    transports: {
      paris: { label: "TER Remiremont + bus", duration: "3h30", priceAR: 40 },
      lyon: { label: "TER via Besançon + bus", duration: "4h30", priceAR: 54 },
      lille: { label: "TGV Nancy + TER + bus", duration: "5h", priceAR: 64 },
      marseille: { label: "TGV via Lyon + TER + bus", duration: "7h", priceAR: 88 },
      bordeaux: { label: "TGV via Paris + TER + bus", duration: "7h30", priceAR: 96 },
    },
    lodging: { dorm: 20, duo: 58 },
    foodPerDay: 14,
    highlights: ["Baignade et pédalo sur le lac", "Cascades et tour des lacs", "Sentiers des Hautes-Vosges"],
    duoTip: "Camping au bord du lac : parmi les moins chers de l'Est.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "chamonix",
    name: "Chamonix",
    code: "CHX",
    region: "Mont-Blanc",
    coords: { lat: 45.9237, lng: 6.8694 },
    vibes: ["montagne"],
    tagline: "La haute montagne accessible en train.",
    transports: {
      paris: { label: "TGV + Mont-Blanc Express", duration: "5h", priceAR: 70 },
      lyon: { label: "TER St-Gervais + Mont-Blanc Express", duration: "4h", priceAR: 44 },
      lille: { label: "TGV via Paris + Express", duration: "6h30", priceAR: 92 },
      marseille: { label: "TGV Lyon + TER + Express", duration: "5h30", priceAR: 66 },
      bordeaux: { label: "TGV via Paris + Express", duration: "7h30", priceAR: 100 },
    },
    lodging: { dorm: 30, duo: 90 },
    foodPerDay: 17,
    highlights: ["Mer de Glace en train à crémaillère", "Lac Blanc, la rando iconique", "Aiguille du Midi (si budget)"],
    duoTip: "Les refuges se réservent : demi-pension parfois plus rentable.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "lyon",
    name: "Lyon",
    code: "LYS",
    region: "Rhône",
    coords: { lat: 45.764, lng: 4.8357 },
    vibes: ["ville"],
    tagline: "Capitale de la bouche, à 2h et 30€.",
    transports: {
      paris: { label: "Ouigo", duration: "2h", priceAR: 30, note: "dès 16€ le trajet" },
      lille: { label: "TGV direct", duration: "3h", priceAR: 58 },
      marseille: { label: "Ouigo / TGV", duration: "1h45", priceAR: 32 },
      bordeaux: { label: "Intercités via Massif ou TGV", duration: "6h", priceAR: 72 },
    },
    lodging: { dorm: 24, duo: 70 },
    foodPerDay: 17,
    highlights: ["Traboules du Vieux Lyon", "Croix-Rousse et ses pentes", "Berges du Rhône à vélo"],
    duoTip: "Bouchon le midi plutôt que le soir : menu à moitié prix.",
    bestMonths: [4, 5, 6, 9, 10],
  },
  {
    slug: "lille",
    name: "Lille",
    code: "LIL",
    region: "Hauts-de-France",
    coords: { lat: 50.6292, lng: 3.0573 },
    vibes: ["ville"],
    tagline: "Week-end flamand à 1h de Paris.",
    transports: {
      paris: { label: "TGV / Ouigo", duration: "1h05", priceAR: 25, note: "dès 10€ le trajet en Ouigo" },
      lyon: { label: "TGV direct", duration: "3h", priceAR: 58 },
      marseille: { label: "TGV direct", duration: "4h40", priceAR: 70 },
      bordeaux: { label: "TGV direct", duration: "5h", priceAR: 82 },
    },
    lodging: { dorm: 23, duo: 65 },
    foodPerDay: 15,
    highlights: ["Vieux-Lille et Grand-Place", "Palais des Beaux-Arts", "Wazemmes le dimanche matin"],
    duoTip: "Bruges ou Gand en TER belge : la Belgique à 30 min.",
    bestMonths: [4, 5, 6, 9, 12],
  },
  {
    slug: "strasbourg",
    name: "Strasbourg",
    code: "SXB",
    region: "Alsace",
    coords: { lat: 48.5734, lng: 7.7521 },
    vibes: ["ville"],
    tagline: "La Petite France, colombages et vélo partout.",
    transports: {
      paris: { label: "TGV / Ouigo", duration: "1h50", priceAR: 30, note: "dès 16€ le trajet" },
      lyon: { label: "TGV direct", duration: "3h40", priceAR: 54 },
      lille: { label: "TGV direct", duration: "3h50", priceAR: 62 },
      marseille: { label: "TGV direct", duration: "5h30", priceAR: 78 },
      bordeaux: { label: "TGV via Paris", duration: "6h", priceAR: 94 },
    },
    lodging: { dorm: 25, duo: 72 },
    foodPerDay: 16,
    highlights: ["Petite France et ponts couverts", "Plateforme de la cathédrale", "Winstubs et tartes flambées"],
    duoTip: "Kehl (Allemagne) en tram : courses et resto moins chers.",
    bestMonths: [4, 5, 6, 9, 12],
  },
];
