import type { Destination } from "./types";

// Prix indicatifs basse saison / résa anticipée, départ Paris, tarifs jeunes
// quand ils existent (Nomad -26 ans = -50%, Ouigo dès 19€). À vérifier avant résa.
export const destinations: Destination[] = [
  {
    slug: "dieppe",
    name: "Dieppe",
    code: "DPE",
    region: "Normandie, côte d'Albâtre",
    vibes: ["mer"],
    tagline: "La mer la moins chère de France depuis Paris.",
    transport: {
      label: "Train Nomad (Saint-Lazare)",
      duration: "2h15",
      priceAR: 20,
      note: "-50% pour les -26 ans, plein tarif 20,10€ le trajet",
    },
    lodging: { dorm: 15, duo: 52 },
    foodPerDay: 15,
    highlights: ["Falaises de craie de Pourville", "Plage et front de mer", "Marché du samedi, port de pêche"],
    duoTip: "Camping en tente partagée : la nuit tombe sous 8€ par personne.",
    bestMonths: [5, 6, 7, 8, 9],
  },
  {
    slug: "le-treport",
    name: "Le Tréport",
    code: "LTR",
    region: "Normandie / Picardie",
    vibes: ["mer"],
    tagline: "Falaises les plus hautes d'Europe, ambiance carte postale.",
    transport: {
      label: "Train + car Nomad",
      duration: "3h",
      priceAR: 24,
      note: "via Abancourt ou Dieppe",
    },
    lodging: { dorm: 16, duo: 55 },
    foodPerDay: 15,
    highlights: ["Funiculaire gratuit vers la falaise", "Plage de galets et casino", "Mers-les-Bains et ses villas 1900"],
    duoTip: "Combinez avec Dieppe : les deux se font en car côtier.",
    bestMonths: [5, 6, 7, 8, 9],
  },
  {
    slug: "etretat",
    name: "Étretat",
    code: "ETR",
    region: "Normandie",
    vibes: ["mer"],
    tagline: "Les falaises que le monde entier vient voir.",
    transport: {
      label: "Train Bréauté + bus",
      duration: "2h45",
      priceAR: 32,
    },
    lodging: { dorm: 24, duo: 78 },
    foodPerDay: 17,
    highlights: ["Arche et Aiguille creuse", "Jardins d'Étretat", "Sentier des douaniers GR21"],
    duoTip: "Dormez au Havre (auberge HI) et venez en bus : deux fois moins cher.",
    bestMonths: [4, 5, 6, 9],
  },
  {
    slug: "deauville",
    name: "Deauville-Trouville",
    code: "DVL",
    region: "Normandie, Côte Fleurie",
    vibes: ["mer"],
    tagline: "Les Planches à 2h de Paris, version étudiante possible.",
    transport: {
      label: "Train Nomad (Saint-Lazare)",
      duration: "2h05",
      priceAR: 30,
      note: "-50% pour les -26 ans",
    },
    lodging: { dorm: 28, duo: 95 },
    foodPerDay: 19,
    highlights: ["Plage et parasols mythiques", "Trouville, le port et la criée", "Villas Belle Époque"],
    duoTip: "Trouville est moins chère que Deauville pour dormir et manger.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "saint-malo",
    name: "Saint-Malo",
    code: "SML",
    region: "Bretagne, Côte d'Émeraude",
    vibes: ["mer"],
    tagline: "Remparts, marées géantes et granit.",
    transport: {
      label: "TGV Inoui / Ouigo",
      duration: "2h30",
      priceAR: 58,
      note: "dès 38€ AR en résa anticipée",
    },
    lodging: { dorm: 26, duo: 80 },
    foodPerDay: 16,
    highlights: ["Tour des remparts au coucher", "Grand Bé à marée basse", "Dinard en navette maritime"],
    duoTip: "L'auberge de jeunesse HI est à 15 min à pied des remparts.",
    bestMonths: [5, 6, 7, 8, 9],
  },
  {
    slug: "la-rochelle",
    name: "La Rochelle",
    code: "LRH",
    region: "Charente-Maritime",
    vibes: ["mer", "ville"],
    tagline: "Vieux-Port, vélo et île de Ré à portée de pédale.",
    transport: {
      label: "TGV / Ouigo",
      duration: "3h",
      priceAR: 50,
      note: "Ouigo dès 19€ le trajet",
    },
    lodging: { dorm: 25, duo: 75 },
    foodPerDay: 16,
    highlights: ["Les trois tours du Vieux-Port", "Île de Ré à vélo (pont gratuit à vélo)", "Marché central et halles"],
    duoTip: "Louez deux vélos à la journée, c'est le vrai bon plan local.",
    bestMonths: [5, 6, 7, 8, 9],
  },
  {
    slug: "biarritz",
    name: "Biarritz",
    code: "BIA",
    region: "Pays basque",
    vibes: ["mer"],
    tagline: "Océan, surf et Pays basque.",
    transport: {
      label: "TGV / Ouigo",
      duration: "4h10",
      priceAR: 70,
      note: "Ouigo dès 25€ le trajet",
    },
    lodging: { dorm: 30, duo: 95 },
    foodPerDay: 18,
    highlights: ["Côte des Basques au coucher", "Rocher de la Vierge", "Bayonne et Saint-Jean-de-Luz en TER"],
    duoTip: "Auberge côté Anglet : moins cher et à 10 min de plage.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "marseille",
    name: "Marseille",
    code: "MRS",
    region: "Provence, Méditerranée",
    vibes: ["mer", "ville"],
    tagline: "Calanques, Vieux-Port et soleil quasi garanti.",
    transport: {
      label: "Ouigo",
      duration: "3h30",
      priceAR: 44,
      note: "dès 19€ le trajet en résa anticipée",
    },
    lodging: { dorm: 28, duo: 78 },
    foodPerDay: 16,
    highlights: ["Calanque de Sormiou en bus + marche", "Vieux-Port et le Panier", "Plages du Prado gratuites"],
    duoTip: "Le bus 21 vers Luminy : les calanques pour 1,70€.",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    slug: "cassis",
    name: "Cassis",
    code: "CSS",
    region: "Provence",
    vibes: ["mer"],
    tagline: "Le village des calanques, eau turquoise.",
    transport: {
      label: "Ouigo Marseille + TER",
      duration: "4h",
      priceAR: 52,
    },
    lodging: { dorm: 30, duo: 92 },
    foodPerDay: 18,
    highlights: ["Calanques d'En-Vau et Port-Pin", "Port de Cassis à l'apéro", "Cap Canaille, route des Crêtes"],
    duoTip: "Dormez à Marseille, venez en TER (25 min) : Cassis coûte cher la nuit.",
    bestMonths: [5, 6, 9],
  },
  {
    slug: "sete",
    name: "Sète",
    code: "SET",
    region: "Occitanie, Méditerranée",
    vibes: ["mer"],
    tagline: "La Venise du Languedoc, plages de sable infinies.",
    transport: {
      label: "Ouigo direct",
      duration: "3h45",
      priceAR: 44,
      note: "dès 19€ le trajet en résa anticipée",
    },
    lodging: { dorm: 27, duo: 72 },
    foodPerDay: 15,
    highlights: ["Plage de la Corniche et lido", "Mont Saint-Clair au coucher", "Canaux, halles et tielles"],
    duoTip: "Les 12 km de lido se longent à vélo, location à la journée pas chère.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "collioure",
    name: "Collioure",
    code: "COL",
    region: "Côte Vermeille, Pyrénées-Orientales",
    vibes: ["mer"],
    tagline: "Le village des peintres, entre mer et Pyrénées.",
    transport: {
      label: "TGV Perpignan + TER",
      duration: "5h30",
      priceAR: 78,
    },
    lodging: { dorm: 29, duo: 88 },
    foodPerDay: 17,
    highlights: ["Château royal et clocher iconique", "Criques du sentier littoral", "Anchois et vin doux locaux"],
    duoTip: "Argelès à 10 min en TER : camping bien moins cher.",
    bestMonths: [5, 6, 9],
  },
  {
    slug: "nice",
    name: "Nice",
    code: "NCE",
    region: "Côte d'Azur",
    vibes: ["mer", "ville"],
    tagline: "La Baie des Anges au tarif Ouigo.",
    transport: {
      label: "Ouigo direct",
      duration: "6h",
      priceAR: 60,
      note: "dès 19€ le trajet, le plus long mais le plus dépaysant",
    },
    lodging: { dorm: 29, duo: 85 },
    foodPerDay: 17,
    highlights: ["Promenade des Anglais à l'aube", "Vieux-Nice et colline du Château", "Villefranche-sur-Mer en TER (10 min)"],
    duoTip: "TER Zou à 1€ le trajet certains jours d'été le long de la côte.",
    bestMonths: [5, 6, 7, 8, 9, 10],
  },
  {
    slug: "annecy",
    name: "Annecy",
    code: "ANN",
    region: "Haute-Savoie",
    vibes: ["lac", "montagne"],
    tagline: "Le lac le plus photogénique de France.",
    transport: {
      label: "TGV",
      duration: "3h50",
      priceAR: 60,
    },
    lodging: { dorm: 28, duo: 85 },
    foodPerDay: 17,
    highlights: ["Baignade au Pâquier, eau à 24°C l'été", "Tour du lac à vélo (42 km)", "Vieille ville et canaux"],
    duoTip: "L'auberge HI est sur les hauteurs : vue lac au petit-déj.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "gerardmer",
    name: "Gérardmer",
    code: "GER",
    region: "Vosges",
    vibes: ["lac", "montagne"],
    tagline: "Lac, forêts et fraîcheur vosgienne, budget mini.",
    transport: {
      label: "TER Remiremont + bus",
      duration: "3h30",
      priceAR: 40,
    },
    lodging: { dorm: 20, duo: 58 },
    foodPerDay: 14,
    highlights: ["Baignade et pédalo sur le lac", "Cascades et tour des lacs", "Sentiers des Hautes-Vosges"],
    duoTip: "Camping au bord du lac : parmi les moins chers de l'Est.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "chamonix",
    name: "Chamonix",
    code: "CHX",
    region: "Mont-Blanc",
    vibes: ["montagne"],
    tagline: "La haute montagne accessible en train.",
    transport: {
      label: "TGV + Mont-Blanc Express",
      duration: "5h",
      priceAR: 70,
    },
    lodging: { dorm: 30, duo: 90 },
    foodPerDay: 17,
    highlights: ["Mer de Glace en train à crémaillère", "Lac Blanc, la rando iconique", "Aiguille du Midi (si budget)"],
    duoTip: "Les refuges se réservent : demi-pension parfois plus rentable.",
    bestMonths: [6, 7, 8, 9],
  },
  {
    slug: "lyon",
    name: "Lyon",
    code: "LYS",
    region: "Rhône",
    vibes: ["ville"],
    tagline: "Capitale de la bouche, à 2h et 30€.",
    transport: {
      label: "Ouigo",
      duration: "2h",
      priceAR: 30,
      note: "dès 16€ le trajet",
    },
    lodging: { dorm: 24, duo: 70 },
    foodPerDay: 17,
    highlights: ["Traboules du Vieux Lyon", "Croix-Rousse et ses pentes", "Berges du Rhône à vélo"],
    duoTip: "Bouchon le midi plutôt que le soir : menu à moitié prix.",
    bestMonths: [4, 5, 6, 9, 10],
  },
  {
    slug: "lille",
    name: "Lille",
    code: "LIL",
    region: "Hauts-de-France",
    vibes: ["ville"],
    tagline: "Week-end flamand à 1h de Paris.",
    transport: {
      label: "TGV / Ouigo",
      duration: "1h05",
      priceAR: 25,
      note: "dès 10€ le trajet en Ouigo",
    },
    lodging: { dorm: 23, duo: 65 },
    foodPerDay: 15,
    highlights: ["Vieux-Lille et Grand-Place", "Palais des Beaux-Arts", "Wazemmes le dimanche matin"],
    duoTip: "Bruges ou Gand en TER belge : la Belgique à 30 min.",
    bestMonths: [4, 5, 6, 9, 12],
  },
  {
    slug: "strasbourg",
    name: "Strasbourg",
    code: "SXB",
    region: "Alsace",
    vibes: ["ville"],
    tagline: "La Petite France, colombages et vélo partout.",
    transport: {
      label: "TGV / Ouigo",
      duration: "1h50",
      priceAR: 30,
      note: "dès 16€ le trajet",
    },
    lodging: { dorm: 25, duo: 72 },
    foodPerDay: 16,
    highlights: ["Petite France et ponts couverts", "Plateforme de la cathédrale", "Winstubs et tartes flambées"],
    duoTip: "Kehl (Allemagne) en tram : courses et resto moins chers.",
    bestMonths: [4, 5, 6, 9, 12],
  },
];
